apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  type: {{ .Values.service.type }}
  selector:
    app: checkout
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http


