applications:
  - key: bookverse-checkout
    seeds:
      application: 2.0.7
      build: 3.28.44
    packages:
      - type: docker
        name: checkout
        seed: 2.38.35
      - type: docker
        name: checkout-api
        seed: 1.17.22
      - type: docker
        name: checkout-worker
        seed: 3.4.11
      - type: docker
        name: checkout-mock-payment
        seed: 3.6.9

