applications:
  - key: bookverse-checkout
    seeds:
      application: 3.2.15
    packages:
      - type: docker
        name: checkout
        seed: 3.2.15
      - type: docker
        name: checkout-worker
        seed: 2.1.12
      - type: docker
        name: checkout-migrations
        seed: 2.0.7
      - type: generic
        name: openapi
        seed: 3.2.15
      - type: generic
        name: order.created.schema
        seed: 3.2.15

